spring:
  application:
    name: cadastro-servicos

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    database: mysql

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/public
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:admin1234}
    hikari:
      connection-timeout: ${HIKARI_TIMEOUT:20000}
      maximum-pool-size: ${HIKARI_POOL_SIZE:5}